language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-25
    - extra-android-m2repository
    - extra-android-suppor
    - add-on
    - extra

notifications:
    email:
        - alessandro.crugnola@gmail.com

cache: false
sudo: false

install:
    # Ensure Gradle wrapper is executable, download wrapper and show version
    - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

    # Download and show android dependencies
    - ./gradlew androidDependencies

script:
  - ./gradlew clean build checkstyleDebug -PdisablePreDex

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle